In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Load  Data

In [2]:
mnist_full = pd.read_csv('./data/train.csv')
mnist_test = pd.read_csv('./data/test.csv')
mnist_full

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0          1       0       0       0       0       0       0       0       0   
1          0       0       0       0       0       0       0       0       0   
2          1       0       0       0       0       0       0       0       0   
3          4       0       0       0       0       0       0       0       0   
4          0       0       0       0       0       0       0       0       0   
...      ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995      0       0       0       0       0       0       0       0       0   
41996      1       0       0       0       0       0       0       0       0   
41997      7       0       0       0       0       0       0       0       0   
41998      6       0       0       0       0       0       0       0       0   
41999      9       0       0       0       0       0       0       0       0   

       pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 785 columns]

In [3]:
mnist_full['label'].value_counts()

1    4684
7    4401
3    4351
9    4188
2    4177
6    4137
0    4132
4    4072
8    4063
5    3795
Name: label, dtype: int64

In [4]:
y = mnist_full['label'].to_numpy()
y

array([1, 0, 1, ..., 7, 6, 9])

In [5]:
X = mnist_full.drop(columns='label').to_numpy().reshape(-1, 28, 28, 1)
X.shape

(42000, 28, 28, 1)

### Split Data

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

In [8]:
X_train.shape

(31500, 28, 28, 1)

## Build Model

In [9]:
import tensorflow as tf
from tensorflow.keras import *

In [34]:
model = Sequential([
    layers.Input(shape=(28, 28, 1)),
    layers.Conv2D(64, (7,7), activation='relu'),
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
    layers.Conv2D(128, (4,4), activation='relu'),
    layers.MaxPooling2D(),
    layers.BatchNormalization(),
    layers.Flatten(),
    layers.Dropout(0.2),
    layers.Dense(512, activation='relu'),
    layers.Dropout(0.2),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [35]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_4 (Conv2D)           (None, 22, 22, 64)        3200      
                                                                 
 max_pooling2d_4 (MaxPooling  (None, 11, 11, 64)       0         
 2D)                                                             
                                                                 
 batch_normalization_4 (Batc  (None, 11, 11, 64)       256       
 hNormalization)                                                 
                                                                 
 conv2d_5 (Conv2D)           (None, 8, 8, 128)         131200    
                                                                 
 max_pooling2d_5 (MaxPooling  (None, 4, 4, 128)        0         
 2D)                                                             
                                                      

In [36]:
model.compile(optimizer=optimizers.SGD(learning_rate=0.09), loss='sparse_categorical_crossentropy', metrics=['acc'])

In [37]:
model.fit(X_train, y_train, 
          epochs=50, 
          batch_size=100, 
          validation_data=[X_val, y_val], 
          validation_batch_size=100, 
          verbose=1)

Epoch 1/50
  1/315 [..............................] - ETA: 1:20 - loss: 3.4318 - acc: 0.0800

2022-03-13 17:49:15.022243: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


313/315 [============================>.] - ETA: 0s - loss: 0.1714 - acc: 0.9452

2022-03-13 17:49:20.748569: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


315/315 [==============================] - 7s 20ms/step - loss: 0.1708 - acc: 0.9454 - val_loss: 0.0597 - val_acc: 0.9810
Epoch 2/50
315/315 [==============================] - 6s 21ms/step - loss: 0.0517 - acc: 0.9844 - val_loss: 0.0376 - val_acc: 0.9886
Epoch 3/50
315/315 [==============================] - 6s 20ms/step - loss: 0.0328 - acc: 0.9893 - val_loss: 0.0482 - val_acc: 0.9842
Epoch 4/50
315/315 [==============================] - 6s 20ms/step - loss: 0.0230 - acc: 0.9920 - val_loss: 0.0421 - val_acc: 0.9866
Epoch 5/50
315/315 [==============================] - 6s 20ms/step - loss: 0.0204 - acc: 0.9926 - val_loss: 0.0383 - val_acc: 0.9890
Epoch 6/50
315/315 [==============================] - 6s 20ms/step - loss: 0.0151 - acc: 0.9950 - val_loss: 0.0348 - val_acc: 0.9891
Epoch 7/50
315/315 [==============================] - 6s 20ms/step - loss: 0.0105 - acc: 0.9965 - val_loss: 0.0367 - val_acc: 0.9906
Epoch 8/50
315/315 [==============================] - 6s 20ms/step - loss: 0.009

### Predict on Test data

In [39]:
mnist_test

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
27995       0       0       0       0       0       0       0       0       0   
27996       0       0       0       0       0       0       0       0       0   
27997       0       0       0       0       0       0       0       0       0   
27998       0       0       0       0       0       0       0       0       0   
27999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
27995       0  ...         0         0         0         0         0   
27996       0  ...         0         0         0         0         0   
27997       0  ...         0         0         0         0         0   
27998       0  ...         0         0         0         0         0   
27999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
27995         0         0         0         0         0  
27996         0         0         0         0         0  
27997         0         0         0         0         0  
27998         0         0         0         0         0  
27999         0         0         0         0         0  

[28000 rows x 784 columns]

In [40]:
X_test = mnist_test.to_numpy().reshape(-1, 28, 28, 1)
X_test.shape

(28000, 28, 28, 1)

In [41]:
y_pred = model.predict(X_test)
y_pred

2022-03-13 17:56:14.498972: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:112] Plugin optimizer for device_type GPU is enabled.


array([[2.5279060e-13, 1.0474506e-15, 1.0000000e+00, ..., 2.2347555e-13,
        5.7032276e-13, 3.0163322e-15],
       [9.9999988e-01, 5.8861175e-12, 1.5923422e-07, ..., 4.1190049e-10,
        1.6565091e-12, 8.6269526e-11],
       [8.2874632e-14, 2.1257010e-13, 3.8981660e-10, ..., 6.0532335e-10,
        9.8697717e-09, 9.9999976e-01],
       ...,
       [4.3910523e-21, 4.7831926e-18, 1.2299962e-18, ..., 1.6978030e-16,
        1.1260816e-16, 7.4203845e-17],
       [1.7577793e-11, 4.5828233e-12, 7.2118783e-11, ..., 1.5458084e-09,
        5.6563407e-09, 9.9999750e-01],
       [1.4587378e-14, 1.5858009e-16, 1.0000000e+00, ..., 1.9769539e-15,
        5.3790440e-12, 2.1117496e-16]], dtype=float32)

In [42]:
predictions = y_pred.argmax(axis=-1)
predictions

array([2, 0, 9, ..., 3, 9, 2])

## Create Submission

In [43]:
submission = pd.DataFrame({'ImageId': range(1, len(y_pred) + 1), 'Label': predictions})
submission

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      9
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [44]:
submission.to_csv('data/submission.csv', index=False)

resnet_v2 = applications.ResNet50V2(include_top=False)

resnet_v2.summary()

for layer in resnet_v2.layers:
    layer.trainable = False

resnet_v2 = applications.ResNet50V2(include_top=False)

resnet_v2.summary()

for layer in resnet_v2.layers:
    layer.trainable = False

resnet_v2 = applications.ResNet50V2(include_top=False)

resnet_v2.summary()

for layer in resnet_v2.layers:
    layer.trainable = False

resnet_v2 = applications.ResNet50V2(include_top=False)

resnet_v2.summary()

for layer in resnet_v2.layers:
    layer.trainable = False